//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public OrderInfo()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string TransactionId { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderInfo OrderInfos1 { get; set; }
        public virtual OrderInfo OrderInfo1 { get; set; }
        public virtual OrderInfo OrderInfos11 { get; set; }
        public virtual OrderInfo OrderInfo2 { get; set; }
        public virtual OrderInfo OrderInfos12 { get; set; }
        public virtual OrderInfo OrderInfo3 { get; set; }
    }
}
